# Flashcards, this will be autogenerated in a final production system
spanish50_limited = """ 
Front: Hola
Back: Hello
---
Front: Adiós
Back: Goodbye
---
Front: Gracias
Back: Thank you
---
Front: Por favor
Back: Please
---
Front: Sí
Back: Yes
---
Front: No
Back: No
---
Front: ¿Cómo estás?
Back: How are you?
---
Front: Bien
Back: Well / Good
---
Front: Mal
Back: Bad
---
Front: ¿Qué tal?
Back: How’s it going?
---
Front: Casa
Back: House
---
Front: Escuela
Back: School
---
Front: Libro
Back: Book
---
Front: Perro
Back: Dog
---
Front: Gato
Back: Cat
---
Front: Comer
Back: To eat
---
Front: Beber
Back: To drink
---
Front: Hablar
Back: To speak
---
Front: Vivir
Back: To live
---
Front: Ir
Back: To go
---
Front: Grande
Back: Big
---
Front: Pequeño
Back: Small
---
Front: Bonito
Back: Pretty / Nice
---
Front: Feo
Back: Ugly
---
Front: Feliz
Back: Happy
---
Front: Triste
Back: Sad
---
Front: Primero
Back: First
---
Front: Segundo
Back: Second
---
Front: Arriba
Back: Up / Above
---
Front: Abajo
Back: Down / Below
---
Front: Dentro
Back: Inside
---
Front: Fuera
Back: Outside
---
Front: Aquí
Back: Here
---
Front: Allí
Back: There
---
Front: Con
Back: With
---
Front: Sin
Back: Without
---
Front: Y
Back: And
---
Front: Pero
Back: But
---
Front: Porque
Back: Because
---
Front: Hombre
Back: Man
---
Front: Mujer
Back: Woman
---
Front: Niño
Back: Boy / Child
---
Front: Niña
Back: Girl / Child
---
Front: Agua
Back: Water
---
Front: Comida
Back: Food
---
Front: Día
Back: Day
---
Front: Noche
Back: Night
---
Front: Mañana
Back: Morning / Tomorrow
---
Front: Tarde
Back: Afternoon / Evening
---
Front: Hoy
Back: Today
---
Front: Ayer
Back: Yesterday
---
Front: Siempre
Back: Always
---
Front: Nunca
Back: Never
---
Front: Rápido
Back: Fast
---
Front: Lento
Back: Slow
---
Front: Bueno
Back: Good
---
Front: Malo
Back: Bad
---
"""


swedish75_limited = """

Front: hej
Back: hello
---
Front: tack
Back: thank you
---
Front: ja
Back: yes
---
Front: nej
Back: no
---
Front: snälla
Back: please
---
Front: förlåt
Back: sorry
---
Front: jag
Back: I
---
Front: du
Back: you
---
Front: han
Back: he
---
Front: hon
Back: she
---
Front: vi
Back: we
---
Front: de
Back: they
---
Front: den
Back: it (common gender)
---
Front: det
Back: it (neuter gender)
---
Front: här
Back: here
---
Front: där
Back: there
---
Front: och
Back: and
---
Front: men
Back: but
---
Front: eller
Back: or
---
Front: med
Back: with
---
Front: utan
Back: without
---
Front: på
Back: on
---
Front: i
Back: in
---
Front: under
Back: under
---
Front: över
Back: over
---
Front: mellan
Back: between
---
Front: före
Back: before
---
Front: efter
Back: after
---
Front: stor
Back: big
---
Front: liten
Back: small
---
Front: lång
Back: long
---
Front: kort
Back: short
---
Front: bra
Back: good
---
Front: dålig
Back: bad
---
Front: varm
Back: warm
---
Front: kall
Back: cold
---
Front: ny
Back: new
---
Front: gammal
Back: old
---
Front: glad
Back: happy
---
Front: ledsen
Back: sad
---
Front: hungrig
Back: hungry
---
Front: törstig
Back: thirsty
---
Front: trött
Back: tired
---
Front: vän
Back: friend
---
Front: familj
Back: family
---
Front: skola
Back: school
---
Front: bok
Back: book
---
Front: mat
Back: food
---
Front: vatten
Back: water
---
Front: kaffe
Back: coffee
---
Front: hund
Back: dog
---
Front: katt
Back: cat
---
Front: springa
Back: to run
---
Front: gå
Back: to walk
---
Front: äta
Back: to eat
---
Front: dricka
Back: to drink
---
Front: sova
Back: to sleep
---
Front: läsa
Back: to read
---
Front: skriva
Back: to write
---
Front: se
Back: to see
---
Front: höra
Back: to hear
---
Front: tala
Back: to speak
---
Front: förstå
Back: to understand
---
Front: köpa
Back: to buy
---
Front: sälja
Back: to sell
---
Front: öppna
Back: to open
---
Front: stänga
Back: to close
---
Front: idag
Back: today
---
Front: imorgon
Back: tomorrow
---
Front: igår
Back: yesterday
---
Front: alltid
Back: always
---
Front: aldrig
Back: never
---
Front: ibland
Back: sometimes
---
Front: mycket
Back: very / a lot
---
Front: lite
Back: a little
---
Front: härlig
Back: lovely
---
Front: enkel
Back: easy / simple
---
Front: svårt
Back: difficult
---
Front: snabb
Back: fast
---
Front: långsam
Back: slow
---
Front: ja, tack
Back: yes, please
---
Front: nej, tack
Back: no, thank you
---


"""
